[bar]
order = ["default"]

[bar.default]
position = "top"
enabled = true
reserve_space = true
layer = "top"
thickness = 40
background_opacity = 0.95
border_width = 0.0
shadow = true
concave_edge_corners = false
radius = 0
radius_top_left = 0
radius_top_right = 0
radius_bottom_left = 10
radius_bottom_right = 10
margin_ends = 0
margin_edge = 0
padding = 14
widget_spacing = 12
font_family = "JetBrainsMono Nerd Font"
font_weight = 400
scale = 1.1
capsule = false
start = ["workspaces", "active_window"]
center = ["clock"]
end = [
  "cpu",
  "ram",
  "temp",
  "network",
  "bluetooth",
  "brightness",
  "output_volume",
  "input_volume",
  "battery",
  "power_profile",
  "caffeine",
  "privacy",
  "clipboard",
  "notifications",
  "tray",
  "session",
]

[widget.workspaces]
style = "regular"
display = "id"
max_label_chars = 2
labels_only_when_occupied = false
hide_when_empty = false
active_pill_size = 2.8
inactive_pill_size = 1.4
focused_color = "primary"
occupied_color = "secondary"
empty_color = "surface_variant"
urgent_color = "error"

[widget.active_window]
display = "text_only"
min_length = 40
max_length = 180
title_scroll = "none"
show_empty_label = false
color = "primary"

[widget.clock]
format = "{:%-I:%M %p}"
tooltip_format = "{:%A, %B %d, %Y}"
color = "primary"
font_weight = 800

[widget.cpu]
type = "sysmon"
stat = "cpu_usage"
display = "text"
show_label = true
label_show_units = false
color = "primary"

[widget.ram]
type = "sysmon"
stat = "ram_pct"
display = "text"
show_label = true
label_show_units = false
color = "primary"

[widget.temp]
type = "sysmon"
stat = "cpu_temp"
display = "text"
show_label = true
label_show_units = false
color = "primary"

[widget.network]
show_label = true
color = "primary"

[widget.bluetooth]
show_label = false
hide_when_no_connected_device = true

[widget.brightness]
show_label = true
color = "primary"

[widget.output_volume]
type = "volume"
device = "output"
show_label = true
color = "primary"

[widget.input_volume]
type = "volume"
device = "input"
show_label = false
color = "primary"

[widget.battery]
display_mode = "glyph"
show_label = true
label_content = "percent"
color = "primary"

[widget.power_profile]
color = "primary"

[widget.caffeine]
color = "primary"

[widget.privacy]
hide_inactive = true
icon_spacing = 6

[widget.notifications]
hide_when_no_unread = true

[widget.tray]
match_adjacent_spacing = true

[widget.session]
color = "primary"

